# Generated by Django 6.0.8 on 2026-09-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0060_item_description_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='printablesUrl',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
