# Generated by Django 6.0.8 on 2026-09-14 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0061_alter_project_printablesurl'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='ActiveDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-day'],
                'indexes': [models.Index(fields=['day'], name='atlantis_si_day_ac9340_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'day'), name='active_day_once_per_user')],
            },
        ),
    ]
