# Generated by Django 6.0.8 on 2026-09-21 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0062_profile_last_seen_activeday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PearlBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_index', models.PositiveSmallIntegerField()),
                ('minutes_paid', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['user_id', 'week_index'],
            },
        ),
        migrations.CreateModel(
            name='PrinterClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_slug', models.CharField(max_length=32)),
                ('printer_name', models.CharField(max_length=60)),
                ('pearls_spent', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaverCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_index', models.PositiveSmallIntegerField()),
                ('source', models.CharField(choices=[('purchase', 'Bought in the shop'), ('admin', 'Granted by an organizer')], default='purchase', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeekOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_index', models.PositiveSmallIntegerField()),
                ('real_minutes', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('override', models.CharField(blank=True, choices=[('', 'No override'), ('P', 'Forced pass'), ('F', 'Forced fail')], default='', max_length=1)),
                ('override_note', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['user_id', 'week_index'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='kind',
            field=models.CharField(choices=[('regular', 'Regular item'), ('saver_current', 'Streak saver — this week'), ('saver_past', 'Streak saver — earliest missed week'), ('printer', 'Printer claim (hidden from the shop)')], default='regular', help_text='Savers are applied on purchase and never reach fulfillment.', max_length=16),
        ),
        migrations.AddField(
            model_name='item',
            name='printer_key',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='profile',
            name='printer_track',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('printer_key__gt', '')), fields=('printer_key',), name='one_item_per_printer'),
        ),
        migrations.AddField(
            model_name='pearlbracket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pearl_brackets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='printerclaim',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printer_claims', to='atlantis_site.order'),
        ),
        migrations.AddField(
            model_name='printerclaim',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='printer_claim', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savercredit',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savers_granted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savercredit',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saver_credits', to='atlantis_site.order'),
        ),
        migrations.AddField(
            model_name='savercredit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saver_credits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weekoutcome',
            name='override_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='week_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weekoutcome',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_outcomes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='pearlbracket',
            constraint=models.UniqueConstraint(fields=('user', 'week_index'), name='one_bracket_per_user_week'),
        ),
        migrations.AddIndex(
            model_name='savercredit',
            index=models.Index(fields=['user', 'week_index'], name='atlantis_si_user_id_fcbc5e_idx'),
        ),
        migrations.AddIndex(
            model_name='weekoutcome',
            index=models.Index(fields=['week_index'], name='atlantis_si_week_in_83f45a_idx'),
        ),
        migrations.AddConstraint(
            model_name='weekoutcome',
            constraint=models.UniqueConstraint(fields=('user', 'week_index'), name='one_outcome_per_user_week'),
        ),
    ]
