# Generated by Django 6.0.8 on 2026-09-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0064_printer_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='t3',
            name='payout_layers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
