# Generated by Django 6.0.8 on 2026-09-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0065_t3_payout_layers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='kind',
            field=models.CharField(choices=[('regular', 'Regular item'), ('saver_current', 'Streak saver: this week'), ('saver_past', 'Streak saver: earliest missed week'), ('printer', 'Printer claim (hidden from the shop)')], default='regular', help_text='Savers are applied on purchase and never reach fulfillment.', max_length=16),
        ),
    ]
